### ISSUE TITLE
link to Structure and Interpretation of Computer Programs

### ISSUE THREAD

**Issue by kdabwl** [Alamvic/druid#100]
Hello,

the link appears to be https://web.mit.edu/6.001/6.037/sicp.pdf

B.t.w. good read :-)

**Comment by Ducasse** [comment]
We already read it long time ago. Now I do not see the point to add an issue here.

**Comment by kdabwl** [comment]
> We already read it long time ago. Now I do not see the point to add an issue here.

writing a ´comment´ is not an issue, git knows that and titles it comment.

**Comment by guillep** [comment]
Hi @kdabwl , yes, that is the correct link, I'll update the readme, thanks!

**Comment by Ducasse** [comment]
Hi @kdabwl Sorry I did not see that the readme had a wrong link on SICP. So tx for the link
We have from time to time strange people opening issues not related to the projects.
