### ISSUE TITLE
Fix the CI !!!

### ISSUE THREAD

**Issue by PalumboN** [Alamvic/druid#125]
We should check why we have broken tests, skip all of them and open an issue for each suite.

With that at least we came back to have a green CI and it's easier to develop avoiding bugs🚦 

Then we can attack the problems when it's time to.

**Comment by guillep** [comment]
After the work on https://github.com/Alamvic/druid/pull/128 and https://github.com/Alamvic/druid/pull/127 we only have 2 remaining tests (each failing for each config).

```
DRProductionPrimitiveCompilationTest
✗ #testCompilePrimitiveAtOnNonArray (6667ms)
✗ #testCompilePrimitiveAtOnNonArray (6643ms)
✗ #testPrimitiveValuePushReceiver (261ms)
✗ #testPrimitiveValuePushReceiver (263ms)
```

**Comment by guillep** [comment]
Tests are green in the latest build. See https://github.com/Alamvic/druid/pull/148
